version: '3'

services:

    mysql:
      image: mysql:5.7.29
      environment:
        - MYSQL_DATABASE=spring-boot-mysql_db
        - MYSQL_ROOT_PASSWORD=root
      ports:
         - "3308:3306"

    webapp:
      image: adoptopenjdk/openjdk11:alpine-jre
      depends_on:
        - mysql
        - redis
      volumes:
        #- ./application-prod.yml:/app/application-prod.yml
        - ./build/libs/spring-boot-mysql-0.0.1-SNAPSHOT.jar:/app/app.jar
      ports:
        - "8080:8080"
#      command: "java -jar /app/app.jar --spring.profiles.active=prod --spring.config.location=/app/application-prod.yml"
      command: "java -jar /app/app.jar"

    redis:
      image: redis